baseURL = "http://miltrump.github.io/"
languageCode = "en-us"
title = "Miltrump's Tech Blog"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Milner Trump - All rights reserved"
disqusShortname = "miltrumptech"
googleAnalytics = "UA-1XXXXXXX1-X"
[params]
  logo = "/images/icon.png"
  description = "the clean blog!"
  mailchimp = "you can provide a mailchimp-link here, see below"
  mailprotect = "you can provide a protector-name here, see below"
  customCSS = []
[params.author]
  name = "John Doe"
  thumbnail = "/images/author.jpg"
  description = "Creator of this blog."
[params.index]
  picture = "/images/author.jpg"
  title = "John Doe"
  subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading'''
  alertbar = true
[params.social]
  github = "<username>"
  linkedin = "<username>"
  xing = "<username>"
  medium = "<username>"
  twitter = "<username>"
  instagram = "<username>"
